backend:
  name: github
  repo: relram3/ramzi.dev
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Skills"
            name: "skills"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
